### ISSUE TITLE
在腾讯云函数部署时遇到问题

### ISSUE THREAD

**Issue by 20150561000** [marigold233/lenovo-sign#10]
![image](https://user-images.githubusercontent.com/59476046/202846446-2dbed7b7-6574-45ef-b8b4-1eb3328a1fff.png)
132行的：
`    if cookie_dict := config.get("cookies").get(username):`
报错为：
`invalid syntax (<unknown>, line 132)`
返回结果为：
`{"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 696, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 677, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 724, in exec_module\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 860, in get_code\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 791, in source_to_code\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 132\n    if cookie_dict := config.get(\"cookies\").get(username):\n                    ^\nSyntaxError: invalid syntax","requestId":"2bbc69e4-dffb-44d3-9dd4-d5fae610c3d5","statusCode":443}`

**Comment by marigold233** [comment]
3.7 好像不支持海象运算符，3.8才支持，请部署到阿里云函数。
