### ISSUE TITLE
大佬，关于青龙面板的教程可否再细致一点，没看懂😭😭😭

### ISSUE THREAD

**Issue by zhougjstudy** [marigold233/lenovo-sign#15]

**Comment by marigold233** [comment]
是不知道怎么上传脚本吗

**Comment by zhougjstudy** [comment]
> 是不知道怎么上传脚本吗

是的，因为之前用的都是傻瓜式操作，但是不太懂原理，导致大佬的脚本不知道怎么装，等有空的了大佬优化下可以吗

**Comment by marigold233** [comment]
- https://noteshare.space/note/clcli870p211301pjctqkxi9r#v3QB7KIC5EbJAAYIPSb/l2uQyXR64bMqUKoscRakv80

图片看不清的话，右击选择”在新标签页选择图像“

**Comment by zhougjstudy** [comment]
> * https://noteshare.space/note/clcli870p211301pjctqkxi9r#v3QB7KIC5EbJAAYIPSb/l2uQyXR64bMqUKoscRakv80
> 
> 图片看不清的话，右击选择”在新标签页选择图像“

感谢大佬❤️
