### ISSUE TITLE
企业微信推送失效

### ISSUE THREAD

**Issue by xulingran** [marigold233/lenovo-sign#18]
按`config.toml`里的格式填写了企业id、应用secret和应用id，但在输出中仅有
`
2023-02-15 09:09:03,271 - INFO: 180xxxxxxx3 ck没有错
`
签到也是成功的，**但是没有企业微信的推送**，麻烦大佬解答一下
（手机号是正确的）

**Comment by marigold233** [comment]
看下这个，现在申请微信应用消息要配置可信IP
https://github.com/pppscn/SmsForwarder/wiki/2.%E5%8F%91%E9%80%81%E9%80%9A%E9%81%93#%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E5%BA%94%E7%94%A8%E6%B6%88%E6%81%AF

**Comment by xulingran** [comment]
可以了，感谢
