### ISSUE TITLE
能否适配一下青龙面板

### ISSUE THREAD

**Issue by keaiye** [marigold233/lenovo-sign#2]

**Comment by marigold233** [comment]
你好

你完全可以把仓库中的`lenovo_sign.py`和`config.toml`复制到青龙面板，然后安装一些依赖，测试执行。

**Comment by keaiye** [comment]
> 你好
> 
> 你完全可以把仓库中的`lenovo_sign.py`和`config.toml`复制到青龙面板，然后安装一些依赖，测试执行。

OK
