### ISSUE TITLE
请教 阿里云函数报错

### ISSUE THREAD

**Issue by Anran0205** [marigold233/lenovo-sign#25]
{
    "errorMessage": "Unable to import module 'index'",
    "errorType": "ImportModuleError",
    "stackTrace": [
        "ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+",
        "currently the 'ssl' module is compiled with 'OpenSSL 1.1.0l  10 Sep 2019'. See: https://github.com/urllib3/urllib3/issues/2168"
    ]
}
![image](https://github.com/marigold233/lenovo-sign/assets/47858902/d64f212a-e47a-46e1-be45-ec6e5e31cb95)

**Comment by marigold233** [comment]
把这些删掉：
![image](https://github.com/marigold233/lenovo-sign/assets/62014410/4acbfac1-bcc6-4911-b1bf-99d1a2a2272f)
执行下面试试？：
```sh
pip3 install requests==2.27 toml -t .
```

**Comment by Anran0205** [comment]
> 把这些删掉： ![image](https://user-images.githubusercontent.com/62014410/246708690-4acbfac1-bcc6-4911-b1bf-99d1a2a2272f.png) 执行下面试试？：
> 
> ```shell
> pip3 install requests==2.27 toml -t .
> ```

配置成功，谢谢
