### ISSUE TITLE
每日签到数据获取问题

### ISSUE THREAD

**Issue by nanotouch** [marigold233/lenovo-sign#9]
每日第一次签到后，获取乐豆，延保会为NONE
![image](https://user-images.githubusercontent.com/52226706/198775119-7dea577c-0cf8-4551-bc3b-7acfcc5f5af4.png)

**Comment by marigold233** [comment]
注意你的手机号隐私，这个问题就是获取不到乐豆数量和延保数量，接口的问题应该是。返回的是一个html，而不是一个json。
![image](https://user-images.githubusercontent.com/62014410/198771974-f04efef3-03ac-42fd-8f17-dbf540290f7c.png)

**Comment by marigold233** [comment]
主要看成功不成功就行了。

**Comment by nanotouch** [comment]
好滴
